# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZFPassword' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZFPassword

 pod 'FMDB'
 pod 'pop', '~> 1.0'
 pod 'Masonry'
 pod 'MBProgressHUD', '~> 1.0.0'


  target 'ZFPasswordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZFPasswordUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
